### ISSUE TITLE
Question about a_ij

### ISSUE THREAD

**Issue by zedzx1uv** [ShannonAI/Self_Explaining_Structures_Improve_NLP_Models#1]
Hi! Thanks for ur sharing. I have carefully read the paper and the code but I am confused that if the model output one a_ij at one inference time. For a sentence of N words, do I need to input the sentence with different ij to obtain importance score?

**Comment by zijunsun** [comment]
For a sentence of N words, at one time inference, we output all a_ij at the same time, where 0<=i<=N and i<=j<=N.

**Comment by zijunsun** [comment]
For a sentence of N words, at one time inference, we output all a_ij at the same time, where 0<=i<=N and i<=j<=N.   
In our code , the variate a_ij is a tensor which indicate scores for all span in one sentence.

**Comment by zedzx1uv** [comment]
Got it.Thx for your prompt reply.
